config/routes.rb
Rails.application.routes.draw do
    mount ActionCable.server => "/cable"
  namespace :admin do
    get 'users/index'
    get 'users/edit', to: "users#edit", as: "user_edit"
    patch 'users/:id/update', to: "users#update", as: "user_update"
    get 'users/new', to: "users#new", as: "user_new"
    post 'users/', to: "users#create", as: "user_create"
    delete 'users/:id', to: "users#destroy", as: "user_destroy"
  end
  namespace :admin do
    #resources :rooms, only: [:index,:new,:create,:destroy,:update]
    get 'rooms/index'
    get 'rooms/edit', to: "rooms#edit", as: "room_edit"
    patch 'rooms/:id/update', to: "rooms#update", as: "room_update"
    get 'rooms/new', to: "rooms#new", as: "room_new"
    post 'rooms/', to: "rooms#create", as: "room_create"
    delete 'rooms/:id', to: "rooms#destroy", as: "room_destroy"
    patch 'rooms/:id/add_user_view_rights', to:"rooms#add_user_view_rights", as:"room_add_user_view_rights"
    patch 'rooms/:id/del_user_view_rights', to:"rooms#del_user_view_rights", as:"room_del_user_view_rights"
    patch 'rooms/:id/add_user_post_rights', to:"rooms#add_user_post_rights", as:"room_add_user_post_rights"
    patch 'rooms/:id/del_user_post_rights', to:"rooms#del_user_post_rights", as:"room_del_user_post_rights"
    patch 'rooms/:id/add_group_rights', to:"rooms#add_group_rights", as:"room_add_group_rights"
    patch 'rooms/:id/del_group_rights', to:"rooms#del_group_rights", as:"room_del_group_rights"
  end
  namespace :admin do
    #resources :groups, only: [:index,:new,:create,:destroy]
    get 'groups/index'
    get 'groups/edit', to: "groups#edit", as: "group_edit"
    get 'groups/new', to: "groups#new", as: "group_new"
    post 'groups/', to: "groups#create", as: "group_create"
    delete 'groups/:id', to: "groups#destroy", as: "group_destroy"
    patch 'groups/:id/add_pupil', to: "groups#add_pupil", as: "group_add_pupil"
    patch 'groups/:id/del_pupil', to: "groups#del_pupil", as: "group_del_pupil"
  end
  #devise_for :users#, controllers: {sessions: "user_sessions"}, only: :sessions#, skip: :registration
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#welcome"
  get '/login' => 'user_sessions#new'
post '/login' => 'user_sessions#create'
get '/logout' => 'user_sessions#destroy'


  # rooms
  get 'rooms/:id', to:"rooms#show", as:"room"
  # documents
  get "docs/:id/serve", to: "documents#serve", as: "doc_serve"
  # folders
  get "folders/:id", to: "folders#show", as: "folder_show"
  get "folders/:id/add_child", to:"folders#add_child", as: "folder_add_child"
  post "folders/", to: "folders#create", as: "folder_create"
  delete "folders/:id", to:"folders#destroy", as: "folder_delete"
  get "folders/:id/edit", to: "folders#edit", as: "folder_edit"
  patch "folders/:id/edit", to: "folders#update", as: "folder_update"
  #
  get "folders/:id/docs/add", to:"folders#add_doc", as: "folder_add_doc"
  post "folders/:id/docs/create_or_update", to:"folders#create_or_update_doc", as: "folder_create_or_update_doc"
  get "folders/:id/docs/:doc_id/propose_new_folder", to:"folders#propose_new_folder_for_doc", as: "folder_propose_new_folder_for_doc"
  patch "folders/:id/docs/:doc_id/mode", to:"folders#move_doc", as:"folder_move_doc"
  get "folders/:id/docs/:doc_id/edit", to:"folders#edit_doc", as: "folder_edit_doc"
  patch "folders/:id/docs/:doc_id", to:"folders#update_doc", as: "folder_update_doc"
  delete "folders/:id/docs/:doc_id", to:"folders#destroy_doc", as:"folder_delete_doc"
  # chat_rooms
  get 'chat_rooms/:id', to:"chat_rooms#show", as:"chat_room"
  post "chat_rooms/:id/chat_posts/:id", to: "chat_rooms#send_post", as: "chat_room_send_post"
  get "chat_post/:id/show", to: "chat_rooms#ws_show_post"
  delete "chat_post/:id", to: "chat_rooms#delete_post", as: "chat_room_delete_chat_post"
  get "chat_post/:id/delete", to: "chat_rooms#ws_delete_post"
  get "chat_post/add_attachment", to:"chat_rooms#add_attachment_to_post", as: 'chat_room_add_attachment_to_chat_post'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
PASSWORD_FORMAT = /\A
  (?=.{8,})          # Must contain 8 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
/x
#  (?=.*[[:^alnum:]]) # Must contain a symbol

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
    has_secure_password
###  has_and_belongs_to_many :groups, join_table: "group_compositions" 
###  has_many :room_rights, class_name: "RoomUserRight"

  validates :name, presence: true
  validates :password, presence: true, format: { with: PASSWORD_FORMAT }, confirmation: true, on: :create
  #before_create :generate_authentication_token

  scope :pupils, -> {where("admin=false AND teacher=false AND questioner=false")}
  scope :staff, -> {where("teacher=true OR questioner=true")}
  scope :teachers, -> {where("teacher=true")}
  scope :questioners, -> {where("questioner=true")}

  def fullname
      (self.firstname.to_s+" "+self.name.to_s).strip
  end
  def viewable_rooms
      if self.admin
          return Room.all
      elsif self.is_pupil?
          return Room.where("id IN (SELECT DISTINCT room_id FROM room_group_rights WHERE group_id IN (SELECT groups.id FROM groups JOIN group_compositions ON groups.id=group_compositions.group_id WHERE user_id=?))",self.id)
      else
          coll=room_rights.select{|rr| rr.view}.map{|rr| Room.find(rr.room_id)}
          if self.teacher
              coll+= Room.where("for_teachers=true").to_a
          end
          if self.questioner
              coll+= Room.where("for_questioners=true").to_a
          end
          return coll
      end
  end
  def editable_rooms
      if self.admin
          return Room.all
      elsif self.is_pupil?
          return []
      else
          coll=room_rights.select{|rr| rr.view}.map{|rr| Room.find(rr.room_id)}
          if self.teacher
              coll+= Room.where("for_teachers=true").to_a
          end
          if self.questioner
              coll+= Room.where("for_questioners=true").to_a
          end
          return coll
      end
  end
  private
  def is_pupil?
      !(self.admin || self.teacher || self.questioner)
  end
def generate_authentication_token
    loop do
      self.auth_token = SecureRandom.base64(64)
      break unless User.find_by(auth_token: auth_token)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user! 

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
helper_method :current_user

  def welcome
    @current_user=current_user
  end

private
  def authenticate_user!
      Rails.logger.info "AUTHENTICATE"
      Rails.logger.info session.to_hash
      unless user=current_user
          redirect_to '/login'
      end
    cookies.signed[:user_id] = session[:user_id]
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    skip_before_action :authenticate_user!

    layout 'log'

    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            flash[:notice]="Authentification réussie"
            Rails.logger.info "Authentification réussie"
            Rails.logger.info session.to_hash
            redirect_to '/'#, token: user.auth_token
        else
            flash[:notice]="Email ou mot de passe invalide"
            Rail.logger.info "Email ou mot de passe invalide"
            redirect_to '/login'
        end
    end
    def destroy
        session[:user_id] = nil
        flash[:notice]="Déconnecté"
        redirect_to '/login'
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/application/_flash.html.erb
<div id="flash">
    <%= flash[:error] %>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
</div>

app/views/application/_user_mainbar.html.erb
<li>Ateliers:
    <ul id="rooms-list">
        < current_user.viewable_rooms.each do |room|%>
            <li><=link_to room.name, room_path(room) %></li>
        < end %>
    </ul>
</li>

app/views/application/welcome.html.erb
<%= render partial: "flash", locals: {flash:flash} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%=ENT_NAME%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      
      <div id="main-bar" class="normal">
          <span id="main-actions"><%=link_to link_to image_tag("links/logout_link.png",alt:"Déconnexion",title:"Déconnexion", size: 36), '/logout'%></span>
          <ul id="main-list">
            <% if current_user.admin? %>
                <%= render partial: "admin/mainbar" %>
            <% else %>
                <%= render partial: "application/user_mainbar" %>
            <% end %>
          </ul>
          <ul>
              <li><%#link_to "Personnel", edit_user_path(current_user) %></li>
              <%#render partial: "rooms/rooms_bar" %>
          </ul>
      </div>
      
      
      <div id="mainframe">
        <%= yield %>
      </div>
  </body>
</html>

app/views/layouts/log.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=ENT_NAME%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/user_sessions/new.html.erb
<h2>Bienvenue sur Taupinière Fauriel</h2>
<%= form_tag '/login' do %>
      <%= label_tag 'Email'%>
      <%= text_field_tag :email, params[:email] %>
      <br>
      <%= label_tag 'Mot de passe'%>
      <%= password_field_tag :password %></p> 

      <%= submit_tag "Log In" %>
          
<% end %>